name: CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x
      - name: Navigate to project directory
        working-directory: ./BookRentalSystem
        run: pwd
      - name: Restore dependencies
        working-directory: ./BookRentalSystem
        run: dotnet restore BookRentalSystem.sln
      - name: Build
        working-directory: ./BookRentalSystem
        run: dotnet build BookRentalSystem.sln --no-restore
